create or replace task CUSTOMER_360_DB.RAW.CHECK_COMPLETENESS_TASK
	warehouse=COMPUTE_WH
	schedule='15 MINUTE'
	as INSERT INTO CUSTOMER_360_DB.RAW.CUSTOMER_LOAD_COMPLETE (CUSTOMER_ID)
  SELECT c.CUSTOMER_ID
  FROM CUSTOMER_360_DB.RAW.RAW_CUSTOMERS c
  WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER_360_DB.RAW.CUSTOMER_LOAD_COMPLETE lc WHERE lc.CUSTOMER_ID = c.CUSTOMER_ID)
    AND EXISTS (SELECT 1 FROM CUSTOMER_360_DB.RAW.RAW_POLICIES p WHERE p.CUSTOMER_ID = c.CUSTOMER_ID)
    AND EXISTS (SELECT 1 FROM CUSTOMER_360_DB.RAW.RAW_CLAIMS cl WHERE cl.CUSTOMER_ID = c.CUSTOMER_ID)
    AND EXISTS (SELECT 1 FROM CUSTOMER_360_DB.RAW.RAW_CALL_TRANSCRIPTS ct WHERE ct.CUSTOMER_ID = c.CUSTOMER_ID)
    AND EXISTS (SELECT 1 FROM CUSTOMER_360_DB.RAW.RAW_INTERACTIONS i WHERE i.CUSTOMER_ID = c.CUSTOMER_ID);