create or replace task CUSTOMER_360_DB.RAW.NOTIFY_NEW_CUSTOMER_TASK
	warehouse=COMPUTE_WH
	after CUSTOMER_360_DB.RAW.CHECK_COMPLETENESS_TASK
	when SYSTEM$STREAM_HAS_DATA('CUSTOMER_360_DB.RAW.LOAD_COMPLETE_STREAM')
	as CALL CUSTOMER_360_DB.RAW.NOTIFY_NEW_CUSTOMER_PROC();