create or replace TABLE CUSTOMER_360_DB.RAW.RAW_INTERACTIONS (
	INTERACTION_ID VARCHAR(10) NOT NULL,
	CUSTOMER_ID VARCHAR(10),
	INTERACTION_DATE TIMESTAMP_NTZ(9),
	CHANNEL VARCHAR(20),
	INTERACTION_TYPE VARCHAR(30),
	SUBJECT VARCHAR(200),
	CONTENT VARCHAR(16777216),
	SENTIMENT_LABEL VARCHAR(20),
	RESOLVED BOOLEAN,
	AGENT_ID VARCHAR(10),
	primary key (INTERACTION_ID),
	foreign key (CUSTOMER_ID) references CUSTOMER_360_DB.RAW.RAW_CUSTOMERS(CUSTOMER_ID)
);