create or replace TABLE CUSTOMER_360_DB.RAW.RAW_CLAIMS (
	CLAIM_ID VARCHAR(10) NOT NULL,
	POLICY_ID VARCHAR(10),
	CUSTOMER_ID VARCHAR(10),
	CLAIM_DATE DATE,
	CLAIM_TYPE VARCHAR(50),
	CLAIM_AMOUNT NUMBER(10,2),
	APPROVED_AMOUNT NUMBER(10,2),
	STATUS VARCHAR(20),
	DESCRIPTION VARCHAR(500),
	HOSPITAL_NAME VARCHAR(100),
	RESOLUTION_DATE DATE,
	RESOLUTION_DAYS NUMBER(38,0),
	SATISFACTION_SCORE NUMBER(38,0),
	primary key (CLAIM_ID),
	foreign key (POLICY_ID) references CUSTOMER_360_DB.RAW.RAW_POLICIES(POLICY_ID),
	foreign key (CUSTOMER_ID) references CUSTOMER_360_DB.RAW.RAW_CUSTOMERS(CUSTOMER_ID)
);