create or replace semantic view CUSTOMER_360_DB.ANALYTICS.CUSTOMER_360_SV
	tables (
		CUSTOMER_360_DB.ANALYTICS.CUSTOMER_360
	)
	facts (
		CUSTOMER_360.ANNUAL_INCOME as ANNUAL_INCOME,
		CUSTOMER_360.TOTAL_ANNUAL_PREMIUM as TOTAL_ANNUAL_PREMIUM,
		CUSTOMER_360.TOTAL_AMOUNT_CLAIMED as TOTAL_AMOUNT_CLAIMED,
		CUSTOMER_360.TOTAL_AMOUNT_APPROVED as TOTAL_AMOUNT_APPROVED,
		CUSTOMER_360.AVG_RESOLUTION_DAYS as AVG_RESOLUTION_DAYS,
		CUSTOMER_360.AVG_CLAIM_SATISFACTION as AVG_CLAIM_SATISFACTION,
		CUSTOMER_360.AVG_CALL_SENTIMENT as AVG_CALL_SENTIMENT,
		CUSTOMER_360.WORST_CALL_SENTIMENT as WORST_CALL_SENTIMENT,
		CUSTOMER_360.AVG_INTERACTION_SENTIMENT as AVG_INTERACTION_SENTIMENT,
		CUSTOMER_360.OVERALL_SENTIMENT_SCORE as OVERALL_SENTIMENT_SCORE
	)
	dimensions (
		CUSTOMER_360.CUSTOMER_ID as CUSTOMER_ID,
		CUSTOMER_360.FULL_NAME as FULL_NAME,
		CUSTOMER_360.EMAIL as EMAIL,
		CUSTOMER_360.PHONE as PHONE,
		CUSTOMER_360.CITY as CITY,
		CUSTOMER_360.STATE as STATE,
		CUSTOMER_360.CUSTOMER_SEGMENT as CUSTOMER_SEGMENT,
		CUSTOMER_360.TENURE_MONTHS as TENURE_MONTHS,
		CUSTOMER_360.CREDIT_SCORE as CREDIT_SCORE,
		CUSTOMER_360.PREFERRED_CHANNEL as PREFERRED_CHANNEL,
		CUSTOMER_360.IS_ACTIVE as IS_ACTIVE,
		CUSTOMER_360.TOTAL_POLICIES as TOTAL_POLICIES,
		CUSTOMER_360.ACTIVE_POLICIES as ACTIVE_POLICIES,
		CUSTOMER_360.LAPSED_POLICIES as LAPSED_POLICIES,
		CUSTOMER_360.POLICY_TYPES as POLICY_TYPES,
		CUSTOMER_360.TOTAL_CLAIMS as TOTAL_CLAIMS,
		CUSTOMER_360.SETTLED_CLAIMS as SETTLED_CLAIMS,
		CUSTOMER_360.PENDING_CLAIMS as PENDING_CLAIMS,
		CUSTOMER_360.REJECTED_CLAIMS as REJECTED_CLAIMS,
		CUSTOMER_360.TOTAL_CALLS as TOTAL_CALLS,
		CUSTOMER_360.TOTAL_INTERACTIONS as TOTAL_INTERACTIONS,
		CUSTOMER_360.UNRESOLVED_ISSUES as UNRESOLVED_ISSUES,
		CUSTOMER_360.CHANNELS_USED as CHANNELS_USED,
		CUSTOMER_360.CHURN_RISK as CHURN_RISK,
		CUSTOMER_360.CALL_HISTORY as CALL_HISTORY,
		CUSTOMER_360.LAST_CALL_DATE as LAST_CALL_DATE
	)
	comment='Customer 360 semantic view providing a unified view of insurance customers including demographics, policy portfolio, claims history, call center interactions, sentiment scores, and churn risk assessment.'
	ai_verified_queries (
		"0;1" AS ( 
QUESTION 'How many customers are in each segment and what is their average premium?' 
VERIFIED_AT 1787814999
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT CUSTOMER_SEGMENT, COUNT(*) AS customer_count, AVG(TOTAL_ANNUAL_PREMIUM) AS avg_premium FROM customer_360 GROUP BY CUSTOMER_SEGMENT'),
		"1;1" AS ( 
QUESTION 'What is the distribution of customers by churn risk level and their average sentiment?' 
VERIFIED_AT 1787814999
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT CHURN_RISK, COUNT(*) AS customer_count, AVG(OVERALL_SENTIMENT_SCORE) AS avg_sentiment FROM customer_360 GROUP BY CHURN_RISK'),
		"2;1" AS ( 
QUESTION 'Which high churn-risk customers have the highest premiums?' 
VERIFIED_AT 1787814999
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT FULL_NAME, CUSTOMER_SEGMENT, CHURN_RISK, TOTAL_ANNUAL_PREMIUM, OVERALL_SENTIMENT_SCORE, UNRESOLVED_ISSUES FROM customer_360 WHERE CHURN_RISK = ''High'' ORDER BY TOTAL_ANNUAL_PREMIUM DESC')
	)
	with extension (CA='{"tables":[{"name":"CUSTOMER_360","dimensions":[{"name":"CUSTOMER_ID"},{"name":"FULL_NAME"},{"name":"EMAIL"},{"name":"PHONE"},{"name":"CITY"},{"name":"STATE"},{"name":"CUSTOMER_SEGMENT"},{"name":"TENURE_MONTHS"},{"name":"CREDIT_SCORE"},{"name":"PREFERRED_CHANNEL"},{"name":"IS_ACTIVE"},{"name":"TOTAL_POLICIES"},{"name":"ACTIVE_POLICIES"},{"name":"LAPSED_POLICIES"},{"name":"POLICY_TYPES"},{"name":"TOTAL_CLAIMS"},{"name":"SETTLED_CLAIMS"},{"name":"PENDING_CLAIMS"},{"name":"REJECTED_CLAIMS"},{"name":"TOTAL_CALLS"},{"name":"TOTAL_INTERACTIONS"},{"name":"UNRESOLVED_ISSUES"},{"name":"CHANNELS_USED"},{"name":"CHURN_RISK"},{"name":"CALL_HISTORY"}],"facts":[{"name":"ANNUAL_INCOME"},{"name":"TOTAL_ANNUAL_PREMIUM"},{"name":"TOTAL_AMOUNT_CLAIMED"},{"name":"TOTAL_AMOUNT_APPROVED"},{"name":"AVG_RESOLUTION_DAYS"},{"name":"AVG_CLAIM_SATISFACTION"},{"name":"AVG_CALL_SENTIMENT"},{"name":"WORST_CALL_SENTIMENT"},{"name":"AVG_INTERACTION_SENTIMENT"},{"name":"OVERALL_SENTIMENT_SCORE"}],"time_dimensions":[{"name":"LAST_CALL_DATE"}]}]}');