create or replace TABLE CUSTOMER_360_DB.RAW.RAW_POLICIES (
	POLICY_ID VARCHAR(10) NOT NULL,
	CUSTOMER_ID VARCHAR(10),
	POLICY_TYPE VARCHAR(30),
	POLICY_SUBTYPE VARCHAR(50),
	PREMIUM_AMOUNT NUMBER(10,2),
	COVERAGE_AMOUNT NUMBER(12,2),
	START_DATE DATE,
	END_DATE DATE,
	PAYMENT_FREQUENCY VARCHAR(20),
	STATUS VARCHAR(20),
	RISK_CATEGORY VARCHAR(10),
	LAST_RENEWAL_DATE DATE,
	AUTO_RENEW BOOLEAN,
	primary key (POLICY_ID),
	foreign key (CUSTOMER_ID) references CUSTOMER_360_DB.RAW.RAW_CUSTOMERS(CUSTOMER_ID)
);