create or replace TABLE CUSTOMER_360_DB.RAW.RAW_CALL_TRANSCRIPTS (
	TRANSCRIPT_ID VARCHAR(10) NOT NULL,
	CUSTOMER_ID VARCHAR(10),
	CALL_DATE TIMESTAMP_NTZ(9),
	AGENT_ID VARCHAR(10),
	CALL_DURATION_SECONDS NUMBER(38,0),
	CALL_TYPE VARCHAR(30),
	CALL_REASON VARCHAR(50),
	TRANSCRIPT_TEXT VARCHAR(16777216),
	RAW_JSON VARIANT,
	LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (TRANSCRIPT_ID),
	foreign key (CUSTOMER_ID) references CUSTOMER_360_DB.RAW.RAW_CUSTOMERS(CUSTOMER_ID)
);